---
- hosts: all
  become: yes
  vars:
    zbx_srv: zabbix.office.uhurulabs.org
    el8_zabbix_repo: https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm
    debian8_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+jessie_all.deb
    debian8_file: zabbix-release_4.4-1+jessie_all.deb
    debian9_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+stretch_all.deb
    debian9_file: zabbix-release_4.4-1+stretch_all.deb
    debian10_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+buster_all.deb
    debian10_file: zabbix-release_4.4-1+buster_all.deb
    ubuntu16_link: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+xenial_all.deb
    ubuntu16_file: zabbix-release_4.4-1+xenial_all.deb
    ubuntu18_link: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+bionic_all.deb
    ubuntu18_file: zabbix-release_4.4-1+bionic_all.deb
    ubuntu20_link: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    ubuntu20_file: zabbix-release_5.0-1+focal_all.deb
  roles:
    - zabbix-agent
