---
- hosts: all
  become: yes
  remote_user: ansible
  vars:
    zbx_srv: zabbix.office.uhurulabs.org
    centos7_link: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
    debian8_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+jessie_all.deb
    debian8_file: zabbix-release_4.4-1+jessie_all.deb
    debian9_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+stretch_all.deb
    debian9_file: zabbix-release_4.4-1+stretch_all.deb
    debian10_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+buster_all.deb
    debian10_file: zabbix-release_4.4-1+buster_all.deb
    ubuntu16_link: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+xenial_all.deb
    ubuntu16_file: zabbix-release_4.4-1+xenial_all.deb
    ubuntu18_link: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+bionic_all.deb
    ubuntu18_file: zabbix-release_4.4-1+bionic_all.deb
  roles:
    - zabbix-agent
