---
##### Install zabbix-agent
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}

### RPM
- name: disable SELinux
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- rpm_key:
    state: present
    key: https://repo.zabbix.com/zabbix-official-repo.key
  when: ansible_os_family == "RedHat"

- name: Add Zabbix Repo
  yum:
    name: " {{ el8_zabbix_repo }}"
  when: ansible_os_family == "RedHat"
  
- name: install zabbix-agent 5.2-1.el8
  yum:
    name: zabbix-agent-5.2.1-1.el8.x86_64
    enablerepo: zabbix
    update_cache: true
    state: latest
  when: ansible_os_family == "RedHat"

### Debian 8
- name: download zabbix deb file for Debian 8
  get_url:
    url: "{{ debian8_link }}"
    dest: "/tmp/{{ debian8_file }}"
  when: ansible_distribution_release == 'jessie'

- name: install zabbix deb in Debian 8
  apt: deb="/tmp/{{ debian8_file }}"
  when: ansible_distribution_release == 'jessie'

- name: install zabbix-agent 4.4 Debian 8
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'jessie'

### Debian 9
- name: download zabbix deb file for Debian 9
  get_url:
    url: "{{ debian9_link }}"
    dest: "/tmp/{{ debian9_file }}"
  when: ansible_distribution_release == 'stretch'

- name: install zabbix deb in Debian 9
  apt: deb="/tmp/{{ debian9_file }}"
  when: ansible_distribution_release == 'stretch'

- name: install zabbix-agent 4.4 Debian 9
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'stretch'

### Debian 10
- name: download zabbix deb file for Debian 10
  get_url:
    url: "{{ debian10_link }}"
    dest: "/tmp/{{ debian10_file }}"
  when: ansible_distribution_release == 'buster'

- name: install zabbix deb in Debian 10
  apt: deb="/tmp/{{ debian10_file }}"
  when: ansible_distribution_release == 'buster'

- name: install zabbix-agent 4.4 Debian 10
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'buster'

### Ubuntu 16.04 Xenial
- name: download zabbix deb file fot Ubuntu 16.04
  get_url:
    url: "{{ ubuntu16_link }}"
    dest: "/tmp/{{ ubuntu16_file }}"
  when: ansible_distribution_release == 'xenial'

- name: install zabbix deb for Ubuntu 16.04 Xenial
  apt: deb="/tmp/{{ ubuntu16_file }}"
  when: ansible_distribution_release == 'xenial'

- name: install zabbix-agent 4.4 Ubuntu 16.04
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'xenial'


### Ubuntu 18.04 Bionic Beaver
- name: download zabbix deb file fot Ubuntu 18.04
  get_url:
    url: "{{ ubuntu18_link }}"
    dest: "/tmp/{{ ubuntu18_file }}"
  when: ansible_distribution_release == 'bionic'

- name: install zabbix deb for Ubuntu 18.04 Xenial
  apt: deb="/tmp/{{ ubuntu18_file }}"
  when: ansible_distribution_release == 'bionic'

- name: install zabbix-agent 4.4 Ubuntu 18.04
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'bionic'
  
### Ubuntu 20
- name: download zabbix deb file fot Ubuntu 20
  get_url:
    url: "{{ ubuntu20_link }}"
    dest: "/tmp/{{ ubuntu20_file }}"
  when: ansible_distribution_release == 'focal'

- name: install zabbix deb for Ubuntu 18.04 Xenial
  apt: deb="/tmp/{{ ubuntu18_file }}"
  when: ansible_distribution_release == 'focal'

- name: install zabbix-agent 5 Ubuntu 20
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'focal'

##### enabled zabbix-agent
- name: enable service zabbix-agent and ensure it is not masked
  systemd:
    name: zabbix-agent
    enabled: yes
    masked: no
  become: yes

##### check zabbix home dir and shell
- name: Make sure a service is stopped
  systemd: state=stopped name=zabbix-agent
  become: yes

- name: check zabbix home dir and shell
  user:
    name: zabbix
    shell: /bin/bash
    home: /etc/zabbix
  become: yes

##### mkdir /etc/zabbix/scripts and rights
- name: mkdir /etc/zabbix/scripts and rights
  file:
    path: /etc/zabbix/scripts
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0700
  become: yes

##### change zabbix_agentd.conf
- name: change zabbix_agentd.conf Hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Hostname=Zabbix server'
    line: "Hostname={{ ansible_hostname }}"
  become: yes

- name: change zabbix_agentd.conf ServerActive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'ServerActive=127.0.0.1'
    line: "ServerActive={{ zbx_srv }}"
  become: yes

- name: change zabbix_agentd.conf Server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Server=127.0.0.1'
    line: "Server={{ zbx_srv }}"
  become: yes

- name: change zabbix_agentd.conf EnableRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
  become: yes

- name: change zabbix_agentd.conf LogRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# LogRemoteCommands=0'
    line: 'LogRemoteCommands=1'

### Starting zabbix-agent
- name: Make sure a service is started
  systemd: state=started name=zabbix-agent
  become: yes
