---
##### Install qemu-agent
- name: ping hosts
  ping:

- name: check OS
  debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}



- name: install qemu-guest-agent
  yum:
    name: qemu-guest-agent
    update_cache: true
    state: latest
  when: ansible_os_family == "CentOS"


- name: install qemu-guest-agent Ubuntu 18.04
  apt:
    name: qemu-guest-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'bionic'

- name: install qemu-guest-agent Ubuntu 20
  apt:
    name: qemu-guest-agent
    state: latest
    update_cache: yes
  when: ansible_distribution_release == 'focal'

##### enabled qemu-guest-agent
- name: enable service qemu-guest-agent and ensure it is not masked
  systemd:
    name: qemu-guest-agent
    enabled: yes
    masked: no
  become: yes

#
### Starting qemu-guest-agent
- name: Make sure a service is started
  systemd: state=started name=qemu-guest-agent
  become: yes
